### ISSUE TITLE
web audio nodes in subpatch

### ISSUE THREAD

**Issue by artofmus** [zauner/vvvv.js#25]
Found the problem. Web audio nodes can not be connected with io box (node) and it makes it impossible to work in sub-patches?

**Comment by zauner** [comment]
I think this is related to the problem I observed with (Node) nodes + audio nodes in general. For example: connect two *Oscillator*s with different frequencies to a *Switch (Node)*, and the output to the *AudioDestination*. When switching the switch, you'd expect to hear different tones, But it stays with the first one.

I think it is because the audio nodes only react to connection changes (connect/disconnect), but don't care about pinIsChanged(). I had a look a the code and tried for a quick fix, but wasn't successful.

Can you help, @geloescht ?

**Comment by geloescht** [comment]
Hmm... maybe it's time for some restructuring of the really fragile connection maintenance code. Right now it reacts to connection changes only because I thought that would be enough to basically mirror the connections to the Web Audio API. But probably the information about audio connections should be inside the _data_. This means getting rid of audioConnectionChanged, apiIndex and apiName on audio nodes and replacing them by a data object, which we transport between nodes via the normal setValue() -> evaluate() -> pinIsChanged() -> getValue() routine.

**Comment by geloescht** [comment]
OK, I found there's a catch with this idea: We not only need to establish new Web Audio connections but also disconnect the old ones, when a vvvvjs connection changes. Right now, this works because the _outgoing_ nodes are responsible for maintaining Web Audio connections. They simply re-establish every outgoing Web Audio connection. Nodes like Switch (Node) don't know they should do this. In the proposed implementation, the _incoming_ nodes would have to maintain Web Audio connections. However, they do not posess enough information about old data to properly disconnect the previous Web Audio connection. Even worse, browsers currently do not even implement a AudioNode.disconnect() method that can target just one specific Web Audio connection. It's only in the newest proposal of the spec.
I believe this is some kind of chicken-and-egg-situation. How did you solve this with WebGL resources, @zauner?
Maybe every audio node should maintain an internal list of its current connections that it can compare to when a pinIsChanged(). This list should also be consulted in order to re-establish Web Audio connections that we lose due to a deficient implementation of AudioNode.disconnect().

**Comment by geloescht** [comment]
I started on an implementation. It is going to be kinda complicated, keeping track of previous and current connections.
Here are some links to the issue that is preventing an easy implementation in current browsers:
https://github.com/WebAudio/web-audio-api/issues/6
https://bugzilla.mozilla.org/show_bug.cgi?id=1130010
I could not find a corresponding bug report for Chrome

**Comment by artofmus** [comment]
Did I understand correctly? Now to disconnect node from a particular node (not all at once) should be used ChannelSplitterNode and ChannelMergerNode? Is it really so? horror)

**Comment by geloescht** [comment]
@artofmus : No, these two nodes are not even implemented yet. What I discussed before was just some implementation detail.

@zauner : Please review the new implementation in a22c23203f63f6a16293cd0384cf509beb7008b8 . I have tested this positively with Switch (Node) but not subpatches. I have no experience whatsoever with subpatches in vvvv.js.
I am not sure how to handle conventional (non-Web Audio) outputs in AnalyserNode (which should be renamed to FFT, really) and DynamicsCompressor. They require continuous calls to evaluate() but the new implementation only changes pin values when it is required to change a Web Audio connection. Should those nodes have auto_evalute set to true? Or should we call markPinAsChanged() every frame for audio output pins, as before? Both approaches should be safe but I am not sure about the performance implications.
@artofmus : No, these two nodes are not even implemented yet. What I discussed before was just some implementation detail.

@zauner : Please review the new implementation in a22c23203f63f6a16293cd0384cf509beb7008b8 . I have tested this positively with Switch (Node) but not subpatches. I have no experience whatsoever with subpatches in vvvv.js.
I am not sure how to handle conventional (non-Web Audio) outputs in AnalyserNode (which should be renamed to FFT, really) and DynamicsCompressor. They require continuous calls to evaluate() but the new implementation only marks pins as dirty when it is required to change a Web Audio connection. Should those nodes have auto_evalute set to true? Or should we call markPinAsChanged() every frame for audio output pins, as before? Both approaches should be safe but I am not sure about the performance implications.

**Comment by zauner** [comment]
Looks good, and works great with Switch (Node) and IOBox (Node) (no other (Node)-nodes yet). Didn't have the chance to test subpatches, but I'm optimistic that this solved it too.

I think an audio pin marked as changed should mean "the connecting, upstream api node changed", and not "the audio signal changed". Therefore it's fine as it is now, and the Analyser and Compressor nodes should be auto-evaluating.
